apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: connectivity-checker
spec:
  selector:
    matchLabels:
      app: connectivity-checker
  template:
    metadata:
      labels:
        app: connectivity-checker
    spec:
      containers:
        - name: connectivity-checker
          image: ghcr.io/fhlemes/netcheck:v0.0.1
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                for pod in $(kubectl get pods -o jsonpath='{.items[*].status.podIP}'); do
                  if [ "$pod" != "$(hostname -i)" ]; then
                    nc -zv $pod 80 || echo "Connection to $pod failed"
                  fi
                done
                sleep 60
              done
          volumeMounts:
            - name: kubeconfig
              mountPath: /root/.kube
              subPath: config
      volumes:
        - name: kubeconfig
          hostPath:
            path: /root/.kube/config
