apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-analysis
  template:
    metadata:
      labels:
        app: network-analysis
    spec:
      containers:
        - name: network-analysis
          image: ghcr.io/fhlemes/netcheck:v0.0.1
          args: ["netcat", "192.168.1.10", "80"]
          env:
            - name: TARGET_IP
              value: "192.168.1.10"
            - name: TARGET_PORT
              value: "80"
