---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: netcheck-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netcheck-clusterrole
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: netcheck-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: netcheck-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: netcheck-clusterrole
  apiGroup: rbac.authorization.k8s.io
